firstSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls'))
]

music/urls.py
from django.urls import path, re_path
from . import views

app_name = 'music'
urlpatterns = [
    # /music/
    path('',views.index, name='index'),

    # /music/<album_id>/
    re_path(r'^(?P<album_id>[0-9]+)/$',views.detail, name='detail'),

    # /music/<album_id>/favorite/
    re_path(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite')

]

music/models.py
from django.db import models

# Blueprint of your DB

class Album(models.Model):
    artist = models.CharField(max_length=100)
    albumTitle = models.CharField(max_length=150)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=100)

    def __str__(self):
        return self.albumTitle + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=200)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.shortcuts import render, get_object_or_404
from .models import Album, Song


# take user request and respond with something

def index(request):
    all_albums = Album.objects.all()
    return render(request, 'music/index.html', {'all_albums': all_albums})


def detail(request, album_id):
    album = get_object_or_404(Album,pk=album_id)
    return render(request, 'music/detail.html', {'album': album})


def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html', {
            'album': album,
            'error_message': "You didn't select any song",
        })
    else:
        selected_song.is_favorite = not selected_song.is_favorite
        selected_song.save()
        return render(request, 'music/detail.html', {'album': album})

music/templates/music/detail.html
<img src="{{album.album_logo}}">

<h1>{{album.albumTitle}}</h1>
<h3>{{album.artist}}</h3>

{% if error_message %}
    <p><strong> {{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
        <label for="song{{ forloop.counter }}">
            {{ song.song_title }}
             {% if song.is_favorite %}
                <img src="https://bitnami.com/assets/new/star-on.png" />
             {% endif %}
        </label><br>
    {% endfor %}
    <input type="submit" value="Favorite">
</form>

music/templates/music/index.html
<!--loads the path to your static files-->
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!--<link href="https://fonts.googleapis.com/css?family=Coiny" rel="stylesheet" type="text/css">-->
<link href="https://fonts.googleapis.com/css?family=Satisfy|Coiny" rel="stylesheet" type="text/css">
<!--<link href="https://fonts.googleapis.com/css?family=Coiny" rel="stylesheet" type="text/css">-->


<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">


        <!--Header and hamburger button -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <!--<span class="glyphicon glyphicon-menu-hamburger"></span>-->
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
        </div>

        <!--Menu items-->
        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav">
                <!--Albums-->
                <li>
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd"></span>&nbsp; Albums
                    </a>
                </li>

                <!--Songs-->
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-music"></span>&nbsp; Songs
                    </a>
                </li>
            </ul>

            <!--Search bar-->
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <!--Add Album-->
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-add"></span>&nbsp; Add Album
                    </a>
                </li>

                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>

        </div>

    </div>
</nav>

{% if all_albums %}
    <h3>Here are all my albums</h3>
    <ul>
        {% for album in all_albums %}
        <li><a href="{% url 'music:detail' album.id %}">{{album.albumTitle}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h3>You don't have any albums</h3>
{% endif %}